### ISSUE TITLE
Add compatible types

### ISSUE THREAD

**Issue by NoiseDoll** [klenin/Yuzu#66]

**Comment by NoiseDoll** [comment]
For example explicitly with attribute:
```
[YuzuCompatibleWith(new[] { typeof(Frame) }]
public class DialogFrame : Frame
```

Or maybe just a runtime check which checks that all yuzu members are equal.

**Comment by klenin** [comment]
Unfortunately, arbitrary type compatibility is hard,
because deserializers actively store closures around specific fields.
Instead, implemented the simplest case of reading from direct ancestor only.

Another option is to add global type aliases at the level of `TypeSerializer` or `FindType`.
That feature would be useful in case of type renames,
but will not work for mix of original and aliased types.

**Comment by klenin** [comment]
>add global type aliases

Essentially done by 6cc52065d97a1e61d20ec33129dce17d0466f463 and 6cc52065d97a1e61d20ec33129dce17d0466f463
